# Generated by Django 6.1 on 2026-08-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="e.g. 737-800, A320neo", max_length=100),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[
                            ("BOEING", "Boeing"),
                            ("AIRBUS", "Airbus"),
                            ("EMBRAER", "Embraer"),
                            ("BOMBARDIER", "Bombardier"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Tail number, e.g. 5N-ABC", max_length=20, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["manufacturer", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="SeatConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_class",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("BUSINESS", "Business"),
                            ("FIRST", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                ("row_start", models.PositiveIntegerField()),
                ("row_end", models.PositiveIntegerField()),
                (
                    "columns",
                    models.CharField(
                        help_text="e.g. ABCDEF (one letter per seat column)",
                        max_length=10,
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_configurations",
                        to="aircraft.aircraft",
                    ),
                ),
            ],
            options={
                "ordering": ["row_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aircraft", "seat_class"),
                        name="unique_class_per_aircraft",
                    )
                ],
            },
        ),
    ]
