# Generated by Django 6.1 on 2026-08-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aircraft", "0001_initial"),
        ("airports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arriving_routes",
                        to="airports.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departing_routes",
                        to="airports.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10)),
                ("departure_datetime", models.DateTimeField()),
                ("arrival_datetime", models.DateTimeField()),
                ("gate", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (pricing pending)"),
                            ("SCHEDULED", "Scheduled"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                            ("DEPARTED", "Departed"),
                            ("ARRIVED", "Arrived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="flights.route",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=6)),
                ("row", models.PositiveIntegerField()),
                ("column", models.CharField(max_length=1)),
                (
                    "seat_class",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("BUSINESS", "Business"),
                            ("FIRST", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="flights.flightschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["row", "column"],
            },
        ),
        migrations.CreateModel(
            name="FlightClassPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_class",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("BUSINESS", "Business"),
                            ("FIRST", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_prices",
                        to="flights.flightschedule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("flight", "seat_class"), name="unique_price_per_class"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("origin", "destination"), name="unique_route"
            ),
        ),
        migrations.AddConstraint(
            model_name="flightschedule",
            constraint=models.UniqueConstraint(
                fields=("flight_number", "departure_datetime"),
                name="unique_flight_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("flight", "seat_number"), name="unique_seat_per_flight"
            ),
        ),
    ]
