# Generated by Django 6.1 on 2026-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(
                        help_text="e.g. LOS, ABV, JFK", max_length=3, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="e.g. Africa/Lagos", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
    ]
